services:
  calendar-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "5050:5050"
    env_file:
      - "./.env"
    command: npm run dev
  calendar-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: calendar
    volumes:
      - "calendar-db-data:/var/lib/postgresql/data"
volumes:
  calendar-db-data:
