services:
  calendar-app:
    build:
      args:
        NODE_ENV: development
    volumes:
      - "../:/app"
      - "/app/node_modules"
    env_file:
      - "../.dev.env"
    command: npm run dev
